import 'package:flutter_test/flutter_test.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:clipshield/services/license_service.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  setUp(() {
    SharedPreferences.setMockInitialValues({});
  });

  group('LicenseService Cryptographic Math & Validation', () {
    test('Expected Key matches pre-calculated Python HMAC-SHA256 signature', () {
      // Test Vector 1: CS-A1B2-C3D4-E5F6
      const testDevice1 = 'CS-A1B2-C3D4-E5F6';
      final key1 = LicenseService.computeExpectedKey(testDevice1);
      expect(key1, '09FD-2422-B5B6-C4F6');
      expect(LicenseService.verifyKey('09FD-2422-B5B6-C4F6', testDevice1), isTrue);
      expect(LicenseService.verifyKey('09fd-2422-b5b6-c4f6', testDevice1), isTrue);
      expect(LicenseService.verifyKey('09FD2422B5B6C4F6', testDevice1), isTrue);
      expect(LicenseService.verifyKey(' 09FD 2422 B5B6 C4F6 ', testDevice1), isTrue);

      // Additional cross-language test vectors generated by Python HMAC-SHA256
      final vectors = {
        'CS-F61B-AFF6-C7D6': '1AB4-5446-25A0-1EEB',
        'CS-41C0-5523-4B1E': '7FED-2F34-7FD3-0366',
        'CS-2E18-C4F5-D615': 'F5AE-7E0B-697B-0A35',
        'CS-655E-FB47-32FD': '6969-3615-1336-D468',
        'CS-168E-3542-8AE8': '5E71-88A1-3477-C12E',
      };

      vectors.forEach((devId, expectedKey) {
        expect(LicenseService.computeExpectedKey(devId), expectedKey);
        expect(LicenseService.verifyKey(expectedKey, devId), isTrue);
      });
    });

    test('Rejects malformed or incorrect keys', () {
      const dev = 'CS-A1B2-C3D4-E5F6';
      expect(LicenseService.verifyKey('09FD-2422-B5B6-C4F5', dev), isFalse);
      expect(LicenseService.verifyKey('SHORT-KEY', dev), isFalse);
      expect(LicenseService.verifyKey('', dev), isFalse);
    });

    test('Persistent Device ID generation follows CS-XXXX-XXXX-XXXX format', () async {
      final service = LicenseService.instance;
      await service.resetForTesting();
      final id1 = await service.getDeviceId();

      expect(id1.startsWith('CS-'), isTrue);
      final parts = id1.split('-');
      expect(parts.length, 4);
      expect(parts[0], 'CS');
      expect(parts[1].length, 4);
      expect(parts[2].length, 4);
      expect(parts[3].length, 4);

      // Ensure persistence
      final id2 = await service.getDeviceId();
      expect(id2, id1);
    });

    test('Trial rendering and activation lifecycle', () async {
      final service = LicenseService.instance;
      await service.resetForTesting();
      await service.init();

      // Fresh install: not activated, trialCount = 0, canRender = true
      expect(service.isActivated(), isFalse);
      expect(service.trialCount, 0);
      expect(service.canRender(), isTrue);

      // Consume 1 trial render
      await service.consumeTrial();
      expect(service.trialCount, 1);
      expect(service.canRender(), isFalse);

      // Attempt invalid activation
      final invalidSuccess = await service.activate('DEAD-BEEF-CAFE-1234');
      expect(invalidSuccess, isFalse);
      expect(service.isActivated(), isFalse);
      expect(service.canRender(), isFalse);

      // Valid activation
      final deviceId = await service.getDeviceId();
      final validKey = LicenseService.computeExpectedKey(deviceId);
      final validSuccess = await service.activate(validKey);
      expect(validSuccess, isTrue);
      expect(service.isActivated(), isTrue);
      expect(service.canRender(), isTrue);

      // Further trial consumption does not affect activated user
      await service.consumeTrial();
      expect(service.canRender(), isTrue);
    });

    test('WhatsApp URL is correctly generated', () async {
      final service = LicenseService.instance;
      const deviceId = 'CS-7777-8888-9999';
      final url = service.getWhatsAppUrl(deviceId);

      expect(
        url,
        'https://wa.me/923079031153?text=Hello%20ClipShield%20Team,%20I%20want%20to%20activate%20ClipShield%20Pro.%20My%20Device%20ID%20is:%20CS-7777-8888-9999',
      );
    });

    test('Multi-Tier Licensing: Lifetime, Monthly, and Video Pack', () async {
      final service = LicenseService.instance;
      await service.resetForTesting();
      await service.init();
      final devId = await service.getDeviceId();

      // 1. Lifetime Key
      final lifeKey = LicenseService.generateLifetimeKey(devId);
      expect(lifeKey.startsWith('CSL-'), isTrue);
      expect(LicenseService.verifyKey(lifeKey, devId), isTrue);

      // 2. Monthly Key
      final monthlyKey = LicenseService.generateMonthlyKey(devId, days: 30);
      expect(monthlyKey.startsWith('CSM30-'), isTrue);
      final mResult = LicenseService.validateKeyDetailed(monthlyKey, devId);
      expect(mResult.isValid, isTrue);
      expect(mResult.tier, LicenseTier.monthly);
      expect(mResult.parameter, 30);

      // Activate Monthly
      await service.activate(monthlyKey);
      expect(service.isActivated(), isTrue);
      expect(service.currentTier, LicenseTier.monthly);

      // 3. Video Pack Key (5 videos)
      await service.resetForTesting();
      final vpKey = LicenseService.generateVideoPackKey(devId, videoCount: 5);
      expect(vpKey.startsWith('CSV05-'), isTrue);
      final vpResult = LicenseService.validateKeyDetailed(vpKey, devId);
      expect(vpResult.isValid, isTrue);
      expect(vpResult.tier, LicenseTier.videoPack);
      expect(vpResult.parameter, 5);

      // Activate Video Pack
      await service.activate(vpKey);
      expect(service.isActivated(), isTrue);
      expect(service.remainingVideos, 5);

      // Consume 5 renders
      for (int i = 4; i >= 0; i--) {
        await service.consumeTrial();
        expect(service.remainingVideos, i);
      }
      // After 5 renders, video pack is exhausted
      expect(service.isActivated(), isFalse);
      expect(service.canRender(), isFalse);
    });
  });
}
