import 'dart:io';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'package:ffmpeg_kit_flutter_new/ffmpeg_kit.dart';
import 'package:path/path.dart' as path;
import '../models/source_metadata.dart';

class DownloaderService {
  final YoutubeExplode _yt = YoutubeExplode();

  String? getVideoId(String url) {
    url = url.trim();
    if (url.isEmpty) return null;

    final shortsRegExp = RegExp(r'(?:youtube\.com|youtu\.be)\/shorts\/([a-zA-Z0-9_-]{11})');
    final shortsMatch = shortsRegExp.firstMatch(url);
    if (shortsMatch != null && shortsMatch.groupCount >= 1) {
      return shortsMatch.group(1);
    }

    final generalRegExp = RegExp(r'(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=))([a-zA-Z0-9_-]{11})');
    final generalMatch = generalRegExp.firstMatch(url);
    if (generalMatch != null && generalMatch.groupCount >= 1) {
      return generalMatch.group(1);
    }

    try {
      return VideoId.parseVideoId(url);
    } catch (_) {
      return null;
    }
  }

  Future<Video?> getVideoDetails(String url) async {
    final id = getVideoId(url);
    if (id == null) return null;
    try {
      return await _yt.videos.get(id);
    } catch (_) {
      return null;
    }
  }

  /// Fetches title, author, description, keywords and thumbnails for a link.
  ///
  /// Returns null for anything that is not a resolvable YouTube video, so the
  /// caller can simply treat a null as "no preview available".
  Future<SourceMetadata?> fetchMetadata(String url) async {
    final id = getVideoId(url);
    if (id == null) return null;
    try {
      final video = await _yt.videos.get(id);
      final thumbs = video.thumbnails;
      return SourceMetadata(
        videoId: id,
        title: video.title,
        author: video.author,
        description: video.description,
        keywords: video.keywords.toList(),
        thumbnailUrl: thumbs.highResUrl.isNotEmpty
            ? thumbs.highResUrl
            : thumbs.mediumResUrl,
        thumbnailMaxResUrl: thumbs.maxResUrl.isNotEmpty
            ? thumbs.maxResUrl
            : (thumbs.standardResUrl.isNotEmpty
                ? thumbs.standardResUrl
                : thumbs.highResUrl),
        durationSeconds: video.duration?.inSeconds ?? 0,
      );
    } catch (_) {
      return null;
    }
  }

  /// Fetches time-stamped subtitles for the video as a single formatted string.
  Future<String?> fetchSubtitles(String url, Function(String) logCallback) async {
    final id = getVideoId(url);
    if (id == null) return null;

    try {
      logCallback("Fetching closed captions metadata...");
      final manifest = await _yt.videos.closedCaptions.getManifest(id);

      if (manifest.tracks.isEmpty) {
        logCallback("No subtitle tracks found for this video.");
        return null;
      }

      ClosedCaptionTrackInfo? selectedTrack;
      final englishTracks = manifest.tracks
          .where((t) => t.language.code.toLowerCase().startsWith('en'));

      if (englishTracks.isNotEmpty) {
        selectedTrack = englishTracks.firstWhere((t) => !t.isAutoGenerated,
            orElse: () => englishTracks.first);
      } else {
        selectedTrack = manifest.tracks.first;
      }

      logCallback(
          "Retrieving subtitles track: ${selectedTrack.language.name} (${selectedTrack.isAutoGenerated ? 'Auto-generated' : 'Closed Captions'})...");
      final track = await _yt.videos.closedCaptions.get(selectedTrack);

      final StringBuffer srtBuffer = StringBuffer();
      for (var caption in track.captions) {
        final startMs = caption.offset.inMilliseconds;
        final seconds = startMs / 1000.0;
        srtBuffer.writeln("[${seconds.toStringAsFixed(2)}] ${caption.text.replaceAll('\n', ' ')}");
      }

      return srtBuffer.toString();
    } catch (e) {
      logCallback("Notice: Closed captions unavailable: $e");
      return null;
    }
  }

  /// Downloads YouTube video to a destination directory.
  Future<String> downloadVideo({
    required String url,
    required String downloadDir,
    required String quality,
    required Function(double, String) progressCallback,
  }) async {
    final id = getVideoId(url);
    if (id == null) {
      throw Exception("Invalid YouTube URL");
    }

    final videoDetails = await _yt.videos.get(id);
    final cleanTitle = videoDetails.title.replaceAll(RegExp(r'[^\w\-\s]'), '_');
    final outputFilename = "${cleanTitle}_source.mp4";
    final outputPath = path.join(downloadDir, outputFilename);

    final dir = Directory(downloadDir);
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }

    progressCallback(0.05, "Analyzing streams...");
    final manifest = await _yt.videos.streamsClient.getManifest(id);

    final bool useMuxed = manifest.muxed.isNotEmpty && quality != 'high';

    if (useMuxed) {
      return await _downloadMuxedStream(manifest, outputPath, progressCallback, downloadDir);
    } else {
      return await _downloadSeparateStreams(manifest, outputPath, downloadDir, progressCallback);
    }
  }

  Future<String> _downloadSeparateStreams(
    StreamManifest manifest,
    String outputPath,
    String downloadDir,
    Function(double, String) progressCallback,
  ) async {
    if (manifest.videoOnly.isEmpty || manifest.audioOnly.isEmpty) {
      if (manifest.muxed.isNotEmpty) {
        progressCallback(0.12, "Fallback: Separate streams missing, retrieving standard stream...");
        return await _downloadMuxedStream(manifest, outputPath, progressCallback, downloadDir);
      }
      throw Exception("No playable video or audio streams found.");
    }

    var videoStreamInfo = manifest.videoOnly.bestQuality;
    final filtered = manifest.videoOnly.where((s) => s.videoResolution.height <= 1080).toList();
    if (filtered.isNotEmpty) {
      filtered.sort((a, b) => a.videoResolution.height.compareTo(b.videoResolution.height));
      videoStreamInfo = filtered.last;
    }
    final audioStreamInfo = manifest.audioOnly.withHighestBitrate();

    final tempVideoPath = path.join(downloadDir, "temp_video.mp4");
    final tempAudioPath = path.join(downloadDir, "temp_audio.m4a");

    progressCallback(0.15, "Downloading video track...");
    await _downloadStream(videoStreamInfo, tempVideoPath, (p) {
      progressCallback(0.15 + (p * 0.50), "Downloading video: ${(p * 100).toInt()}%");
    });

    progressCallback(0.70, "Downloading audio track...");
    await _downloadStream(audioStreamInfo, tempAudioPath, (p) {
      progressCallback(0.70 + (p * 0.15), "Downloading audio: ${(p * 100).toInt()}%");
    });

    progressCallback(0.85, "Muxing streams...");
    final mergeCommand =
        "-y -i \"$tempVideoPath\" -i \"$tempAudioPath\" -c:v copy -c:a aac -strict experimental \"$outputPath\"";

    final session = await FFmpegKit.execute(mergeCommand);
    final returnCode = await session.getReturnCode();

    try {
      if (await File(tempVideoPath).exists()) await File(tempVideoPath).delete();
      if (await File(tempAudioPath).exists()) await File(tempAudioPath).delete();
    } catch (_) {}

    if (returnCode != null && returnCode.isValueSuccess()) {
      progressCallback(1.0, "Stream acquisition complete!");
      return outputPath;
    } else {
      throw Exception("Failed to merge audio and video tracks.");
    }
  }

  Future<String> _downloadMuxedStream(
    StreamManifest manifest,
    String outputPath,
    Function(double, String) progressCallback,
    String downloadDir,
  ) async {
    if (manifest.muxed.isEmpty) {
      return await _downloadSeparateStreams(manifest, outputPath, downloadDir, progressCallback);
    }
    final muxedStreamInfo = manifest.muxed.bestQuality;

    progressCallback(0.10, "Downloading stream...");
    await _downloadStream(muxedStreamInfo, outputPath, (p) {
      progressCallback(0.10 + (p * 0.85), "Downloading: ${(p * 100).toInt()}%");
    });

    progressCallback(1.0, "Download complete!");
    return outputPath;
  }

  Future<void> _downloadStream(
    StreamInfo streamInfo,
    String savePath,
    Function(double) onProgress,
  ) async {
    final stream = _yt.videos.streamsClient.get(streamInfo);
    final file = File(savePath);
    final output = file.openWrite(mode: FileMode.write);

    final totalBytes = streamInfo.size.totalBytes;
    int bytesDownloaded = 0;

    await for (final data in stream) {
      bytesDownloaded += data.length;
      output.add(data);
      onProgress(bytesDownloaded / (totalBytes > 0 ? totalBytes : 1));
    }

    await output.flush();
    await output.close();
  }

  void dispose() {
    _yt.close();
  }
}
