import 'dart:io';
import 'package:youtube_explode_dart/youtube_explode_dart.dart';
import 'package:ffmpeg_kit_flutter_new/ffmpeg_kit.dart';
import 'package:path/path.dart' as path;

class DownloaderService {
  final YoutubeExplode _yt = YoutubeExplode();

  String? getVideoId(String url) {
    try {
      return VideoId.parseVideoId(url);
    } catch (_) {
      return null;
    }
  }

  Future<Video?> getVideoDetails(String url) async {
    final id = getVideoId(url);
    if (id == null) return null;
    try {
      return await _yt.videos.get(id);
    } catch (_) {
      return null;
    }
  }

  /// Fetches time-stamped subtitles for the video as a single formatted string.
  Future<String?> fetchSubtitles(String url, Function(String) logCallback) async {
    final id = getVideoId(url);
    if (id == null) return null;

    try {
      logCallback("Fetching closed captions metadata...");
      final manifest = await _yt.videos.closedCaptions.getManifest(id);

      if (manifest.tracks.isEmpty) {
        logCallback("No subtitle tracks found for this video.");
        return null;
      }

      ClosedCaptionTrackInfo? selectedTrack;
      final englishTracks = manifest.tracks
          .where((t) => t.language.code.toLowerCase().startsWith('en'));

      if (englishTracks.isNotEmpty) {
        selectedTrack = englishTracks.firstWhere((t) => !t.isAutoGenerated,
            orElse: () => englishTracks.first);
      } else {
        selectedTrack = manifest.tracks.first;
      }

      logCallback(
          "Retrieving subtitles track: ${selectedTrack.language.name} (${selectedTrack.isAutoGenerated ? 'Auto-generated' : 'Closed Captions'})...");
      final track = await _yt.videos.closedCaptions.get(selectedTrack);

      final StringBuffer srtBuffer = StringBuffer();
      for (var caption in track.captions) {
        final startMs = caption.offset.inMilliseconds;
        final seconds = startMs / 1000.0;
        srtBuffer.writeln("[${seconds.toStringAsFixed(2)}] ${caption.text.replaceAll('\n', ' ')}");
      }

      return srtBuffer.toString();
    } catch (e) {
      logCallback("Notice: Closed captions unavailable: $e");
      return null;
    }
  }

  /// Downloads YouTube video to a destination directory.
  Future<String> downloadVideo({
    required String url,
    required String downloadDir,
    required String quality,
    required Function(double, String) progressCallback,
  }) async {
    final id = getVideoId(url);
    if (id == null) {
      throw Exception("Invalid YouTube URL");
    }

    final videoDetails = await _yt.videos.get(id);
    final cleanTitle = videoDetails.title.replaceAll(RegExp(r'[^\w\-\s]'), '_');
    final outputFilename = "${cleanTitle}_source.mp4";
    final outputPath = path.join(downloadDir, outputFilename);

    final dir = Directory(downloadDir);
    if (!await dir.exists()) {
      await dir.create(recursive: true);
    }

    progressCallback(0.05, "Analyzing streams...");
    final manifest = await _yt.videos.streamsClient.getManifest(id);

    if (quality == 'high') {
      progressCallback(0.10, "Fetching high-definition streams...");
      if (manifest.videoOnly.isEmpty || manifest.audioOnly.isEmpty) {
        progressCallback(0.12, "Fallback: HD streams missing, retrieving standard stream...");
        return await _downloadMuxedStream(manifest, outputPath, progressCallback);
      }

      final videoStreamInfo = manifest.videoOnly.bestQuality;
      final audioStreamInfo = manifest.audioOnly.withHighestBitrate();

      final tempVideoPath = path.join(downloadDir, "temp_video.mp4");
      final tempAudioPath = path.join(downloadDir, "temp_audio.m4a");

      progressCallback(0.15, "Downloading video track...");
      await _downloadStream(videoStreamInfo, tempVideoPath, (p) {
        progressCallback(0.15 + (p * 0.50), "Downloading video: ${(p * 100).toInt()}%");
      });

      progressCallback(0.70, "Downloading audio track...");
      await _downloadStream(audioStreamInfo, tempAudioPath, (p) {
        progressCallback(0.70 + (p * 0.15), "Downloading audio: ${(p * 100).toInt()}%");
      });

      progressCallback(0.85, "Muxing streams...");
      final mergeCommand =
          "-y -i \"$tempVideoPath\" -i \"$tempAudioPath\" -c:v copy -c:a aac -strict experimental \"$outputPath\"";

      final session = await FFmpegKit.execute(mergeCommand);
      final returnCode = await session.getReturnCode();

      try {
        await File(tempVideoPath).delete();
        await File(tempAudioPath).delete();
      } catch (_) {}

      if (returnCode != null && returnCode.isValueSuccess()) {
        progressCallback(1.0, "Stream acquisition complete!");
        return outputPath;
      } else {
        throw Exception("Failed to merge audio and video tracks.");
      }
    } else {
      return await _downloadMuxedStream(manifest, outputPath, progressCallback);
    }
  }

  Future<String> _downloadMuxedStream(
    StreamManifest manifest,
    String outputPath,
    Function(double, String) progressCallback,
  ) async {
    if (manifest.muxed.isEmpty) {
      throw Exception("No playable video streams found.");
    }
    final muxedStreamInfo = manifest.muxed.bestQuality;

    progressCallback(0.10, "Downloading stream...");
    await _downloadStream(muxedStreamInfo, outputPath, (p) {
      progressCallback(0.10 + (p * 0.85), "Downloading: ${(p * 100).toInt()}%");
    });

    progressCallback(1.0, "Download complete!");
    return outputPath;
  }

  Future<void> _downloadStream(
    StreamInfo streamInfo,
    String savePath,
    Function(double) onProgress,
  ) async {
    final stream = _yt.videos.streamsClient.get(streamInfo);
    final file = File(savePath);
    final output = file.openWrite(mode: FileMode.write);

    final totalBytes = streamInfo.size.totalBytes;
    int bytesDownloaded = 0;

    await for (final data in stream) {
      bytesDownloaded += data.length;
      output.add(data);
      onProgress(bytesDownloaded / (totalBytes > 0 ? totalBytes : 1));
    }

    await output.flush();
    await output.close();
  }

  void dispose() {
    _yt.close();
  }
}
